services:
  db:
    image: postgres:14
    container_name: eventos_culturales_db
    environment:
      - POSTGRES_DB=eventos_culturales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./init-scripts/dml.sql:/docker-entrypoint-initdb.d/dml.sql
      - ./init-scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: eventos_culturales_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=eventos_culturales
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data:
